[global]
developmentMode = false

[logger]
level = "info"

[client]
caching = true
showSidebarNavigation = true
showErrorDetails = true

[server]
port = 8000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true
runOnSave = false
baseUrlPath = ""
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
fileWatcherType = "auto"
folderWatchBlacklist = ['']
cookieSecret = "a-random-key-appears-here"

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8000

[theme]
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#262730"
font = "sans serif"
